### ISSUE TITLE
Unable to add new item

### ISSUE THREAD

**Issue by blackbull85** [jreklund/php4dvd#85]
Error from nginx error log:

```PHP message: PHP Notice:  Undefined index: parental_guidance in /var/www/php4dvd/includes/movie.inc.php on line 37
PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/php4dvd/includes/movie.inc.php on line 38
PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/php4dvd/includes/movie.inc.php on line 39
PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/php4dvd/lib/db/Movie.class.php on line 85
PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/php4dvd/lib/db/Movie.class.php on line 86
PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/php4dvd/lib/db/Movie.class.php on line 87
PHP message: PHP Warning:  array_keys() expects parameter 1 to be array, null given in /var/www/php4dvd/lib/db/Movie.class.php on line 94
PHP message: PHP Warning:  array_intersect(): Expected parameter 1 to be an array, null given in /var/www/php4dvd/lib/db/Movie.class.php on line 96
PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/php4dvd/lib/db/Movie.class.php on line 29
PHP message: PHP Fatal error:  Uncaught [22007] - SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column php4dvd.movies.pg at row 1 trace:
#0 /var/www/php4dvd/lib/redbean/rb.php(1175): RedBeanPHP\Driver\RPDO->runQuery()
#1 /var/www/php4dvd/lib/redbean/rb.php(1215): RedBeanPHP\Driver\RPDO->GetAll()
#2 /var/www/php4dvd/lib/redbean/rb.php(4455): RedBeanPHP\Driver\RPDO->GetOne()
#3 /var/www/php4dvd/lib/redbean/rb.php(6203): RedBeanPHP\Adapter\DBAdapter->getCell()
#4 /var/www/php4dvd/lib/redbean/rb.php(6334): RedBeanPHP\QueryWriter\AQueryWriter->insertRecord()
#5 /var/www/php4dvd/lib/redbean/rb.php(9157): RedBeanPHP\QueryWriter\AQueryWriter->updateRecord()
#6 /var/www/php4dvd/lib/redbean/rb.php(8523): RedBeanPHP\Repository\Frozen->storeBean() 
```

**Comment by jreklund** [comment]
Have you modified `config/parental.guidance.php` in any way? Because it can't find it anymore.
You also may have made incorrect settings inside your `config/config.php`.

**Comment by blackbull85** [comment]
I've reinstalled everything including the config folder and now it's working again. Thank for the help.
