### ISSUE TITLE
Blank page when saving new title

### ISSUE THREAD

**Issue by nickcharles23** [jreklund/php4dvd#98]
Hi,
Just checking if anyone has seen this issue. I added a new title a few weeks back and when I wanted to add a new title yesterday  I get a blank page when clicking on the save or save and add new title. 

I reinstalled php4dvd using upgrade procedure and cleared browser cache and still get a blank web page after save.  Still using the same php version 8.2 and not aware of any server files being change. This issue seems similar to issue 93 that has been posted. Editing titles seem to be working without any issues.

Here is the imdb data ID I am trying to add is http://localhost/php4dvd/?go=add&imdbid=7733396. All the imdb available data is populated in the fields.  I have 1461 titles save in the MYSQL database.

Can anyone give any guidance on helping resolve this issue. Thanks

**Comment by jreklund** [comment]
Do you have any error logs? Can you add another title except that one?

**Comment by nickcharles23** [comment]
I have checked the php and mysql logs and found nothing.

I can add a new movie title and save it using the search function.

But can't using the hack for adding tv titles as http://localhost/php4dvd/?go=add&imdbid=7733396 or 7733388 both resulting in getting a blank page.

I was able to enter a new tv title with the id 0676168.

Since I can add some tv titles and not others. This leads me to believe it has to do with IMDB fields that have null data being downloaded or non at all /empty. Then pfp4dvd is failing  on saving the data into mysql due to a field in mysql  requiring non null data or an null.  Thus not competing the save process in mysql in resulting seeing a blank page.

Possible fix to ensure the add title page have all fields have a default to be null. Or the mysql schema table fields be set to default val nullable to yes except title and year. Currently all are set to no.

**Comment by jreklund** [comment]
Based on `7733396` and `7733388` compared to `0676168` some number fields aren't populated. Add a 0/1 in those fields and it should save just fine for now.

You should troubleshoot why you aren't getting any error logs as these type of problems will be logged there.

**Comment by luskin72** [comment]
Same here, just now, also without any imdb reference... seems to be related to some empty field (ratings) that are expected not to be null. 

Here is a error.log excerpt:

PHP Fatal error:  Uncaught [22007] - SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect double value: '' for column `lkFilms`.`movies`.`rating` at row 1\ntrace: #0 /var/www/Film/lib/redbean/rb.php(1175): RedBeanPHP\\Driver\\RPDO->runQuery()\n#1 /var/www/Film/lib/redbean/rb.php(1215): RedBeanPHP\\Driver\\RPDO->GetAll()\n#2 /var/www/Film/lib/redbean/rb.php(4455): RedBeanPHP\\Driver\\RPDO->GetOne()\n#3 /var/www/Film/lib/redbean/rb.php(6213): RedBeanPHP\\Adapter\\DBAdapter->getCell()\n#4 /var/www/Film/lib/redbean/rb.php(6344): RedBeanPHP\\QueryWriter\\AQueryWriter->insertRecord()\n#5 /var/www/Film/lib/redbean/rb.php(9162): RedBeanPHP\\QueryWriter\\AQueryWriter->updateRecord()\n#6 /var/www/Film/lib/redbean/rb.php(8534): RedBeanPHP\\Repository\\Frozen->storeBean()\n#7 /var/www/Film/lib/redbean/rb.php(9636): RedBeanPHP\\Repository->store()\n#8 /var/www/Film/lib/redbean/rb.php(12606): RedBeanPHP\\OODB->store()\n#9 /var/www/Film/lib/db/Movies.class.php(19): RedBeanPHP\\Facade::store()\n#10 /var/www/Film/includes/mo...'

Now I've tried to change the db table structure, allowing a null value and default value as 0 for 'rating'.

And then the error is the same but on another column: 'duration'.

PHP Fatal error:  Uncaught [22007] - SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column `lkFilms`.`movies`.`duration` at row 1\ntrace: #0 /var/www/Film/lib/redbean/rb.php(1175): RedBeanPHP\\Driver\\RPDO->runQuery()\n#1 /var/www/Film/lib/redbean/rb.php(1215): RedBeanPHP\\Driver\\RPDO->GetAll()\n#2 /var/www/Film/lib/redbean/rb.php(4455): RedBeanPHP\\Driver\\RPDO->GetOne()\n#3 /var/www/Film/lib/redbean/rb.php(6213): RedBeanPHP\\Adapter\\DBAdapter->getCell()\n#4 /var/www/Film/lib/redbean/rb.php(6344): RedBeanPHP\\QueryWriter\\AQueryWriter->insertRecord()\n#5 /var/www/Film/lib/redbean/rb.php(9162): RedBeanPHP\\QueryWriter\\AQueryWriter->updateRecord()\n#6 /var/www/Film/lib/redbean/rb.php(8534): RedBeanPHP\\Repository\\Frozen->storeBean()\n#7 /var/www/Film/lib/redbean/rb.php(9636): RedBeanPHP\\Repository->store()\n#8 /var/www/Film/lib/redbean/rb.php(12606): RedBeanPHP\\OODB->store()\n#9 /var/www/Film/lib/db/Movies.class.php(19): RedBeanPHP\\Facade::store()\n#10 /var/www/Film/includes...'


Tried the same trick on that column but without result thi time…
really cannot understand why in this case the error isa about "invalid datetime" while the column is a smallint(4) type.
